select * from customers;
select * from menu;
select * from orders;
select * from reservation;
select * from supervisors;
select * from tables;
select * from tableslots;
select * from users;
select * from waiters;